# Generated by Django 3.0 on 2025-08-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
        ('oc_lettings_site', '0002_delete_old_data'),
    ]

    operations = [
    ]
